/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Clases.Jugador;
import javax.swing.JLabel;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
    
/**
 *
 * @author Ricardo Marcano
 */
public class Jugador1 extends javax.swing.JFrame {
    
    String color;
    Jugador player;
    JLabel[][] mapa = new JLabel[15][15];
    String mapatext[][] = {{"H","H","H","H","H","H","H","H","H","H","H","H","H","H","H"},
{"H","S","S","S","S","S","S","S","S","S","S","S","S","S","H"},
{"H","S","H","S","H","S","H","S","H","S","H","S","H","S","H"},
{"H","S","S","S","S","S","S","S","S","S","S","S","S","S","H"},
{"H","S","H","S","H","S","H","S","H","S","H","S","H","S","H"},
{"H","S","S","S","S","S","S","S","S","S","S","S","S","S","H"},
{"H","S","H","S","H","S","H","S","H","S","H","S","H","S","H"},
{"H","S","S","S","S","S","S","S","S","S","S","S","S","S","H"},
{"H","S","H","S","H","S","H","S","H","S","H","S","H","S","H"},
{"H","S","S","S","S","S","S","S","S","S","S","S","S","S","H"},
{"H","S","H","S","H","S","H","S","H","S","H","S","H","S","H"},
{"H","S","S","S","S","S","S","S","S","S","S","S","S","S","H"},
{"H","H","H","H","H","H","H","H","H","H","H","H","H","H","H"},
{"H","H","H","H","H","H","H","H","H","H","H","H","H","H","H"},
{"H","H","H","H","H","H","H","H","H","H","H","H","H","H","H"}};
    
    /**
     * Creates new form Jugador1
     * @param nombre
     * @param apellido
     * @param color
     */
    public Jugador1(String nombre, String apellido,String color) {
        this.color = color;
        player = new Jugador(nombre,apellido,44,130,color);
        initComponents();
        cargarjugador();
        generarmapa();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(657, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*arguments
     */
        private void formKeyPressed(java.awt.event.KeyEvent evt) {                                
        // TODO add your handling code here:
        
        
        if(evt.getKeyCode()== KeyEvent.VK_UP){

        }
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
      
            
        }
        if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            
        }

        if(evt.getKeyCode()== KeyEvent.VK_RIGHT){

        }
        
}

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugador1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new Jugador1().setVisible(true);
        });
    }
    public void generarmapa(){
        JLabel banner = new JLabel();
        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner.png")));
        add(banner);
        banner.setBounds(0,0,647,86);
        banner.validate();
        for(int i=0;i<=14;i++)
            for(int j=0;j<=12;j++){
                mapa[j][i] = new JLabel();
                mapa[j][i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/"+mapatext[j][i]+".png")));
                add(mapa[j][i]);
            }
        
        for(int i=0;i<=14;i++)
            for(int j=0;j<=12;j++){
                mapa[j][i].setBounds(i*43,j*43+86,43,43);
                mapa[j][i].validate();
            }
        
        

    }
    
    public void cargarjugador(){
        player.getBomberman().setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/"+color+".png")));
        add(player.getBomberman());
        player.getBomberman().validate();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
