/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Clases.Bomba;
import Clases.Jugador;
import Clases.Partida;
import javax.swing.JLabel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyListener;
import java.util.Random;

    
/**
 *
 * @author Ricardo Marcano
 */
public class Jugador1 extends javax.swing.JFrame{

   
    int ii=0;
    String color;
    public Jugador player;
    JLabel[][] mapa = new JLabel[15][15];    
    public Partida parti;
    public static int estado=0;
    String[][] paredtxt = new String[15][15];
    Random md = new Random();
    JLabel[][] bloques = new JLabel[15][15];
    public JLabel bomba1=new JLabel();
    public JLabel bomba2=new JLabel();

     

    
    /**
     * Creates new form Jugador1
     * @param nombre
     * @param apellido
     * @param color
     */
    public Jugador1(String nombre, String apellido,String color) {
        this.color = color;
        player = new Jugador(nombre,apellido,44,119,color);
        parti = new Partida(player,null);
        initComponents();
        generaBloquestxt();
        cargarjugador();
        add(bomba1);
        add(bomba2);
        generaBloques();
        generarmapa();
        

        
        //add(bomba);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(657, 700));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_SPACE)
            ponerBomba();
        
        if(evt.getKeyCode()== KeyEvent.VK_DOWN){
            
            player.getBomberman().setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/"+color+"/Front/Bman_F_f0"+ii+".png")));
            player.getBomberman().validate();
            ii++;
            if(ii>7)
                ii=0;
            player.moverAbajo();            
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            
            player.getBomberman().setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/"+color+"/Back/Bman_B_f0"+ii+".png")));
            player.getBomberman().validate();
            ii++;
            if(ii>7)
                ii=0;
            player.moverArriba();            
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            
            player.getBomberman().setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/"+color+"/izquierda/Bman_F_f0"+ii+".png")));
            player.getBomberman().validate();
            ii++;
            if(ii>7)
                ii=0;
            player.moverIzquierda();
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            
            player.getBomberman().setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/"+color+"/Side/Bman_F_f0"+ii+".png")));
            player.getBomberman().validate();
            ii++;
            System.out.print(ii);
            if(ii>7)
                ii=0;
            player.moverDerecha();
        }
            
    }//GEN-LAST:event_formKeyPressed

    public void generaBloquestxt(){
        int x,y,cant;
        cant=0;
        
        while(cant<45){
            do{
            x=(int)(Math.random()*12+2);
            y=(int)(Math.random()*12+2);

            
            }while(parti.mapatext[y][x].equals("H"));

            paredtxt[y][x] = "B";
            cant++;  
        }
            
    }
        
    public void generarmapa(){
        JLabel banner = new JLabel();
        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner.png")));
        add(banner);
        banner.setBounds(0,0,647,86);
        banner.validate();
        for(int i=0;i<=14;i++)
            for(int j=0;j<=12;j++){
                mapa[j][i] = new JLabel();
                mapa[j][i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/"+parti.mapatext[j][i]+".png")));
                add(mapa[j][i]);
            }
        for(int i=0;i<=14;i++)
            for(int j=0;j<=12;j++){
                mapa[j][i].setBounds(i*43,j*43+86,43,43);
                mapa[j][i].validate();
            }
    }
    
    public void generaBloques(){
        
                for(int i=0;i<=14;i++)
            for(int j=0;j<=12;j++){
                if(paredtxt[j][i]!=null)
                if(paredtxt[j][i].equals("B")){
                bloques[j][i] = new JLabel();
                bloques[j][i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/"+paredtxt[j][i]+".png")));
                add(bloques[j][i]);
            }
            }
        for(int i=0;i<=14;i++)
            for(int j=0;j<=12;j++){
                if(paredtxt[j][i]!=null)
                if(paredtxt[j][i].equals("B")){
                bloques[j][i].setBounds(i*43,j*43+86,43,43);
                bloques[j][i].validate();
            }
            }
    }
    
    /**
     *
     */
    public void ponerBomba(){
        bomba1 = new Bomba(player.getX(),player.getY());
        bomba1.setBounds(player.getX(),player.getY(),43,43);
        System.out.println(this.getComponentZOrder(bomba1));
        bomba1.validate();
    }
    
    public void cargarjugador(){
        player.getBomberman().setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/"+color+"/Front/Bman_F_f00.png")));
        add(player.getBomberman());
        player.getBomberman().setBounds(player.getX(), player.getY(), 29, 53);
        player.getBomberman().validate();        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
}

